package de.julianweinelt.caesar.web;

public enum AuditAction {
    CREATE_PLUGIN,
    UPDATE_PLUGIN_PROPS,
    UPDATE_PLUGIN_STATUS,
    DELETE_PLUGIN,
    UPLOAD_PLUGIN_FILE,
    DELETE_PLUGIN_FILE,
    CREATE_ACCOUNT,
    EDIT_ACCOUNT,
    CHANGE_EMAIL,
    CHANGE_PASSWORD,
    DEACTIVATE_ACCOUNT,
    REACTIVATE_ACCOUNT,
    REQUEST_ACCOUNT_DELETION,
    DELETE_ACCOUNT,
    REQUEST_PERSONAL_DATA,
    LOGIN,
    POST_COMMENT,
    DELETE_COMMENT,
}